#!/system/bin/sh
#
# spear_test_battery - recognize spear_test_battery
# Copyright (C) 2012 Vincenzo Frascino <vincenzo.frascino@st.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see .
#

#insmod spear_test_battery.ko
insmod /system/lib/modules/spear_test_battery.ko

sleep 1

setprop status.battery.state Slow
setprop status.battery.level 5
setprop status.battery.level_raw  50
setprop status.battery.level_scale 9

echo "SPEAr test battery Driver Loaded..."
